//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        public int Код { get; set; }
        public int КодСотрудника { get; set; }
        public int КодОборудования { get; set; }
        public string ОписаниеПоломки { get; set; }
        public System.DateTime Дата { get; set; }
        public Nullable<System.DateTime> ДатаДиагностики { get; set; }
        public string ИтогиДиагностики { get; set; }
        public string ОписаниеРемонта { get; set; }
        public Nullable<System.DateTime> ДатаРемонта { get; set; }
        public Nullable<System.DateTime> ДатаОтчета { get; set; }
        public string Отчет { get; set; }
        public Nullable<int> Статус { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Оборудование Оборудование { get; set; }
    }
}
