//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТипОборудования
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТипОборудования()
        {
            this.Оборудование = new HashSet<Оборудование>();
        }
    
        public int Код { get; set; }
        public string Имя { get; set; }
        public double Масса { get; set; }
        public int Частота { get; set; }
        public int ЧислоДвигателей { get; set; }
        public double УсловнаяГлубина { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оборудование> Оборудование { get; set; }
    }
}
